### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by GodwinEbikwo** [pacocoursey/next-themes#18]
Hi, can we set other HTML elements other than the "background" or "colour". Try to set border-colour for each theme but it's not working.

**Comment by pacocoursey** [comment]
Hi, yes. This library has nothing to do with the way you style your website, it simply updates the HTML element so you can refer to it as a CSS selector.

For example, changing the border-color could look like this:

```css
[data-theme="dark"] .my-div {
  /* White on dark mode */
  border-color: white;
}

.my-div {
  /* Black on light mode */
  border-color: black;
}
```
