### ISSUE TITLE
Is using with Material UI or similar possible?

### ISSUE THREAD

**Issue by balazsorban44** [pacocoursey/next-themes#2]
I had a comment about asking to solve this issue @mui-org before: https://github.com/mui-org/material-ui/issues/12827#issuecomment-649595621

But just to be clear, there is probably no workaround to get this work with Material UI and similar libraries without them being able to read CSS variables, right?

**Comment by pacocoursey** [comment]
Great question! 

This library does not rely on your theme styling using CSS variables. You can hard-code the values in your CSS, and everything will work as expected (without any flashing):

```css
html, body {
  color: #000;
  background: #fff;
}

[data-theme="dark"],
[data-theme="dark"] body {
  color: #fff;
  background: #000;
}
```

I added that to the README. A lot of blog posts about dark mode (in fact, every single one...) get something wrong. No need to inject all of your CSS variables at all!
