### ISSUE TITLE
Add theme hints for modern browsers

### ISSUE THREAD

**Issue by 5alidz** [pacocoursey/next-themes#26]
Modern browsers can use this hint to render better scrollbars, inputs, etc. it could be done from css
```css
:root {
  color-scheme: dark;   /* dark | light */
}
```
My workaround is including this somewhere
```tsx
const { resolvedTheme } = useTheme();
useEffect(() => {
  if (typeof window != 'undefined') {
    document.documentElement.style.setProperty('color-scheme', resolvedTheme || 'light');
  }
}, [resolvedTheme]);
```
