### ISSUE TITLE
Auto-set light theme in print mode?

### ISSUE THREAD

**Issue by NateRadebaugh** [pacocoursey/next-themes#6]
My resume looks great in dark theme and light theme, but when printing in dark theme, the browser removes the background but I'm left with the text showing as bad contrast since the site thinks it's still in dark mode.

Is there a good way to better support printing themes?

**Comment by pacocoursey** [comment]
Great question! I haven't thought about print styles in a while.

It may depend on your styling solution, but you can usually use a print media query to inject your desired styles for print. For example, setting your CSS variables back to light mode:

```css
@media print {
  :root {
    --fg: #000;
    --bg: #fff;
    /* light mode variables... */
  }
}
```

Let me know if that works for you!
